# Thanks to Aaron Francis for handy guide: https://aaronfrancis.com/2021/the-perfect-vercel-github-actions-deployment-pipeline
name: Deploy to Vercel
on:
  push:
    branches:
      - master
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}
          restore-keys: ${{ runner.os }}-
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2.1.0
          with:
            version: 6.0.2
            run_install: true
        - name: Build 
          run: |
            pnpm run build
      - name: deploy site to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ secrets.orgId}} #Required
          vercel-project-id: ${{ secrets.projectId}} #Required
          scope: ${{ secrets.orgId }} 

